"""Build manuscript tables/one new plot from archived results. NO model imports or fitting.

Run from any directory: python build_evidence.py
Original manuscripts, predictions, datasets and models are read-only inputs.
"""
from pathlib import Path
import csv
import hashlib
import json
import re
import shutil

ROOT = Path(__file__).resolve().parent
WORK = ROOT.parent.parent
OLD = WORK / "论文修订版_实验问题修复"
SUP = ROOT.parent / "补充实验_20260910"
DOC = ROOT / "正文"
EVID = DOC / "evidence"
TABLES = DOC / "tables"
DATASETS = ["XJTU", "MATR", "Tongji"]
CHAIN = ["B", "B1", "B12", "B123", "B1234"]
GROUPS = ["B", "B1", "B2", "B3", "B4", "B12", "B13", "B14", "B23", "B24", "B34", "B123", "B124", "B134", "B234", "B1234"]
METRICS = ["mae", "rmse", "p95_ae"]
COPIES = []


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def copy(src, dst):
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() and sha(src) != sha(dst):
        raise RuntimeError(f"Refusing to overwrite changed evidence: {dst}")
    if not dst.exists():
        shutil.copy2(src, dst)
    COPIES.append({"source": str(src), "copy": str(dst.relative_to(ROOT)), "sha256": sha(src)})


def read(rel):
    with (EVID / rel).open(newline="") as f:
        return list(csv.DictReader(f))


def esc(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def fmt(value, places=4):
    return f"{float(value):.{places}f}"


def row(values):
    return " & ".join(map(str, values)) + r" \\"


def tab(name, caption, label, spec, header, rows, note="", size="footnotesize", fit=False):
    body = [r"% Generated by build_evidence.py; do not hand-edit numerical entries.",
            r"\begin{table}[!htbp]", r"\centering", r"\caption{" + caption + "}",
            r"\label{tab:" + label + "}", "\\" + size, r"\setlength{\tabcolsep}{4pt}"]
    if fit:
        body.append(r"\resizebox{\columnwidth}{!}{%")
    body += [r"\begin{tabular}{" + spec + "}", r"\toprule", row(header), r"\midrule"]
    body += [r if isinstance(r, str) else row(r) for r in rows]
    body += [r"\bottomrule", r"\end{tabular}"]
    if fit:
        body.append("}")
    if note:
        body += [r"\par\smallskip", r"\begin{minipage}{\columnwidth}\footnotesize " + note + r"\end{minipage}"]
    body += [r"\end{table}", ""]
    (TABLES / (name + ".tex")).write_text("\n".join(body))


def pm(r, metric):
    val = fmt(r[metric + "_mean_pp"])
    sd = r[metric + "_seed_sd_pp"]
    return val + (r"$\pm$" + fmt(sd) if sd else "")


def trip(r, prefix=""):
    return "/".join(fmt(r[prefix + m]) for m in METRICS)


def interval(r, unit):
    return "[" + fmt(r[unit + "_ci_low_pp"]) + ", " + fmt(r[unit + "_ci_high_pp"]) + "]"


def prepare():
    TABLES.mkdir(parents=True, exist_ok=True)
    for name in ["main.tex", "supplementary_material.tex"]:
        copy(OLD / "正文" / name, ROOT / "原稿快照" / name)
    for folder in ["figures_base", "figures_supplement"]:
        for p in sorted((OLD / "正文" / folder).glob("*.png")):
            copy(p, DOC / folder / p.name)
    for folder in ["statistics", "baselines/summary", "external/confirmation/summary"]:
        for p in sorted((SUP / folder).iterdir()):
            if p.suffix in {".csv", ".json"} and p.is_file():
                copy(p, EVID / folder / p.name)
    for name in ["protocol.json", "completion_audit.json", "external/confirmation_data_gate.json", "external/pl_protocol.json", "external/exposure_and_source_lock.json", "external/pl_exposure_audit.json", "external/pl_source_lock.json"]:
        copy(SUP / name, EVID / name)
    for folder, dest in [("图表数据", "figure_data"), ("核心模型", "legacy_core"), ("基线", "legacy_baselines")]:
        for p in sorted((OLD / "证据" / folder).iterdir()):
            if p.is_file() and p.suffix in {".csv", ".json", ".md"}:
                copy(p, EVID / dest / p.name)
    core = ROOT.parent / "模块研发/results/m4_random_function_candidate_v1"
    for name in ["acceptance.json", "candidate.json"]:
        copy(core / name, EVID / "frozen_model" / name)
    copy(core/'source_snapshot/m1/protocol.json', EVID/'frozen_model/input_protocol.json')
    completion=ROOT.parent/'模块研发/results/paper_completion_v1'
    copy(completion/'efficiency/request.json',EVID/'legacy_core/benchmark_environment.json')
    for c in ['CS2_8','CS2_21','CX2_3']:
        copy(SUP/'external/cohort'/f'{c}_audit.json',EVID/'external/cell_audits'/f'{c}_audit.json')
    # Mechanical extraction: retain the original bibliography separately for comparison.
    old = (ROOT / "原稿快照/main.tex").read_text()
    bib = old[old.index(r"\begin{thebibliography}"):old.index(r"\end{thebibliography}") + len(r"\end{thebibliography}")]
    (ROOT / "原稿快照/bibliography_original.tex").write_text(bib + "\n")


def make_tables():
    ab = {(r["dataset"], r["group"]): r for r in read("statistics/full_ablation_16_groups.csv")}
    pairs = {(r["dataset"], r["comparison"], r["metric"]): r for r in read("statistics/paired_intervals.csv")}
    combined = read("baselines/summary/combined_12_baselines_plus_final.csv")
    ix = {(r["dataset"], r["method"]): r for r in combined}
    neural = {(r["dataset"], r["model"], r["setting"]): r for r in read("baselines/summary/comparison.csv")}
    methods = ['Dummy_mean','Support_mean','Last_support','Ridge','PLSR','SVR_RBF','RandomForest','XGBoost','GPR','PatchTSTLite','TCN','MAML_MLP','B1234_frozen']
    assert set(methods) == {r['method'] for r in combined}
    labels = {"Dummy_mean": "Source mean", "Support_mean": "Support mean", "Last_support": "Last support", "SVR_RBF": "SVR-RBF", "RandomForest": "Random Forest", "MAML_MLP": "MAML--MLP", "B1234": "B1234 (frozen)", "B1234_frozen": "B1234 (frozen)"}
    names = lambda s: labels.get(s, esc(s))
    rr = []
    for meth in methods:
        first = ix[("XJTU", meth)]
        rr.append([names(meth), '--' if meth=='B1234_frozen' else first["seeds"], *[pm(ix[(ds, meth)], "mae") for ds in DATASETS]])
        if meth in {"Last_support", "GPR", "MAML_MLP"}:
            rr.append(r"\midrule")
    tab("baseline_mae", "Three-dataset baseline comparison: MAE in SOH percentage points (pp). Lower is better; selection policies are not identical.", "baselines", "lrccc", ["Method", "Seeds", *DATASETS], rr,
        r"The nine legacy references/regressors use an XJTU-frozen global configuration; the three neural implementations use fold-local source validation. Neural $\pm$ values are sample SDs over three seeds, not confidence intervals. Tree baselines retain ten seeds. B1234 is one frozen release, not a three-seed mean. These twelve families include three simple reference rules.", fit=True)
    rr = [[names(m), *[pm(neural[(d,m,"source_bias")], "mae") for d in DATASETS]] for m in ["PatchTSTLite", "TCN", "MAML_MLP"]]
    tab("bias_mae", "Fixed support-mean bias correction for the neural baselines (three seeds). These diagnostic settings are retained alongside, not substituted post hoc for, the source-validation-selected primary settings.", "bias", "lccc", ["Method", *DATASETS], rr, fit=True)
    tab("progressive", "Progressive development ablation. Entries are MAE/RMSE/P95 in SOH pp, with equal cell-within-domain and equal domain weighting.", "progressive", "lccc", ["Configuration", *DATASETS], [[g,*[trip(ab[(d,g)]) for d in DATASETS]] for g in CHAIN], fit=True)
    rr = []
    for d in DATASETS:
        p = pairs[(d,"B1234-B","mae")]
        rr.append([d,p["improved_cells"]+"/"+p["cells"],p["worse_cells"],fmt(p["delta_pp"]),interval(p,"domain")])
    tab("cell_uncertainty", "Cell-level MAE wins and domain-bootstrap intervals for B1234 minus B. Negative differences favour B1234. Intervals describe frozen development predictions, without selection-bias correction.", "celluncertainty", "lrrrc", ["Dataset", "Wins/total", "Losses", r"$\Delta$ (pp)", "95\\% domain CI"], rr)
    rr=[]
    for d in DATASETS:
        b,f=ab[(d,"B")],ab[(d,"B1234")]
        rr.append([d,f["low_cells"],f'{int(f["low_points"]):,}',trip(b,"low_"),trip(f,"low_")])
    tab("low_soh", "Low-SOH errors (stored true SOH $<0.90$), using the same cell--domain weighting as the main metrics. Entries are MAE/RMSE/P95 (pp).", "lowsoh", "lrrcc", ["Dataset", "Cells", "Points", "B", "B1234"], rr, fit=True)
    early={(r["dataset"],r["group"]):r for r in read("statistics/controls_early_B12.csv")}
    final={(r["dataset"],r["group"]):r for r in read("statistics/controls_final_M4.csv")}
    early_names={"GPR":"B", "M1":"B1", "Full_v3":"B12 (M2 v3)", "ordinary_PLS":"Ordinary PLS representation", "ordinary_PLS_half_physical":"PLS + half physical", "physical":"Physical-feature GP"}
    rr=[r"\multicolumn{4}{l}{Earlier B12-stage controls (not final-model replacements)} \\"]
    for g in ["M1","ordinary_PLS","ordinary_PLS_half_physical","physical","Full_v3"]:
        rr.append([early_names[g],*[fmt(early[(d,g)]["mae"]) for d in DATASETS]])
    rr += [r"\midrule",r"\multicolumn{4}{l}{Final M4-stage controls} \\"]
    for g in ["B1234","B1234_function_shared","B1234_slope_private","B1234_slope_shared"]:
        rr.append([names(g).replace(r"\_", " "),*[fmt(final[(d,g)]["mae"]) for d in DATASETS]])
    tab("controls", "Quantitative representation and M4 structural controls: MAE (pp). Ordinary PLS here replaces a representation, and is not the standalone PLSR baseline.", "controls", "lccc", ["Configuration", *DATASETS], rr, fit=True)
    external=read("external/confirmation/summary/cohort_summary.csv")
    tab("external_overall", "Frozen XJTU-to-CALCE confirmation: equal protocol-group and equal source-model weighting. Values are SOH pp, not a direct mean of the seven cell rows.", "externaloverall", "lrrr", ["Configuration","MAE","RMSE","P95"], [[r["group"],*[fmt(r[m+"_pp"]) for m in METRICS]] for r in external])
    cells=read("external/confirmation/summary/cell_mean_across_sources.csv")
    ci={(r["cell_id"],r["group"]):r for r in cells}
    ids=list(dict.fromkeys(r["cell_id"] for r in cells))
    tab("external_cells", "All seven eligible CALCE cells. MAE (pp) is averaged over errors from six frozen XJTU source models; predictions are not ensembled. Each cell contributes ten support measurements in addition to the listed queries.", "externalcells", "lrccccc", ["Cell","Queries",*CHAIN], [[esc(c),ci[(c,"B")]["query"],*[fmt(ci[(c,g)]["mae_pp"]) for g in CHAIN]] for c in ids], fit=True)
    train={(r['dataset'],r['group']):r for r in read('legacy_core/training_comparison.csv')}
    times={(r['dataset'],r['group'],r['requested_queries']):r for r in read('legacy_core/timing_comparison.csv')}
    mem={(r['dataset'],r['group']):r for r in read('legacy_core/memory_comparison.csv')}
    rr=[]
    for d in DATASETS:
        for g in ['B','B1234']:
            rr.append([d,g,fmt(train[(d,g)]['mean_seconds'],2),fmt(times[(d,g,'1')]['mean_fold_median_ms'],2),fmt(mem[(d,g)]['compressed_MiB'],2),fmt(mem[(d,g)]['sampled_prediction_peak_RSS_MiB'],2)])
    tab('complexity','Fixed-configuration CPU cost. Training is seconds per fold; latency is milliseconds per single query; compressed storage and sampled prediction-peak process RSS are MiB.','complexity','llrrrr',['Dataset','Model','Train (s)','Query (ms)','Size (MiB)','RSS (MiB)'],rr,fit=True)
    # Appendices: exact metrics, without hiding losing settings.
    for d in DATASETS:
        tab('all_baselines_'+d, d+' baseline metrics (SOH pp); policies and seed counts follow Table~\\ref{tab:baselines}.', 'allbase'+d,'lccc',['Method','MAE','RMSE','P95'], [[names(m),*[pm(ix[(d,m)],met) for met in METRICS]] for m in methods],fit=True)
        rr=[]
        for m in ['PatchTSTLite','TCN','MAML_MLP']:
            for s in ['inner_selected','source_only','source_bias']:
                rr.append([names(m),{'inner_selected':'Source-val selected','source_only':'Source only','source_bias':'Support bias'}[s],*[pm(neural[(d,m,s)],met) for met in METRICS]])
        tab('neural_'+d,d+' neural settings, all with three seeds. Means and sample SDs are in SOH pp.','neural'+d,'llccc',['Method','Setting','MAE','RMSE','P95'],rr,fit=True)
        tab('all_ablation_'+d,d+' full sixteen-combination development ablation (SOH pp). Low-SOH entries use cell--domain weighting.','allabl'+d,'lcccc',['Group','MAE','RMSE','P95','Low-SOH MAE'],[[g,*[fmt(ab[(d,g)][m]) for m in [*METRICS,'low_mae']]] for g in GROUPS])
        tab('early_controls_'+d,d+' complete earlier B12-stage representation/fusion controls (SOH pp).','early'+d,'lrrr',['Configuration','MAE','RMSE','P95'],[[esc(g),*[fmt(early[(d,g)][m]) for m in METRICS]] for g in sorted(set(r[1] for r in early))],fit=True)
    rr=[]
    for d in DATASETS:
        for g in ['B123','B1234','B1234_function_shared','B1234_slope_private','B1234_slope_shared']:
            rr.append([d,esc(g),*[fmt(final[(d,g)][m]) for m in METRICS]])
    tab('m4_controls','Final-stage M4 structural controls (SOH pp). Shared and private variants have mixed rankings.','m4controls','llrrr',['Dataset','Configuration','MAE','RMSE','P95'],rr,fit=True)
    for metric in ['mae','low_mae']:
        rr=[]
        for d in DATASETS:
            for comp in ['B1-B','B12-B1','B123-B12','B1234-B123','B1234-B']:
                p=pairs[(d,comp,metric)]
                rr.append([d,comp,fmt(p['delta_pp']),interval(p,'cell'),interval(p,'domain')])
        tab('paired_'+metric,('MAE' if metric=='mae' else 'Low-SOH MAE')+' paired intervals (pp), 5,000 resamples. Cell-stratified and domain resampling answer different questions; neither corrects development selection.','paired'+metric.replace('_',''),'llrcc',['Dataset','Comparison',r'$\Delta$','Cell-stratified CI','Domain CI'],rr,fit=True)
    # Historical best-setting-per-method table: separate from prospectively source-selected supplement.
    hist=[r for r in read('legacy_baselines/fair_selection_v1_comparison.csv') if r['track']=='strict']
    if not hist:
        tracks=sorted(set(r['track'] for r in read('legacy_baselines/fair_selection_v1_comparison.csv')))
        raise RuntimeError('Inspect legacy track names: '+str(tracks))
    chosen={}
    for r in hist:
        key=r['method']
        if key not in chosen or float(r['mae_mean'])<float(chosen[key]['mae_mean']):chosen[key]=r
    assert len(chosen)==19, len(chosen)
    rr=[]
    for m,r in sorted(chosen.items(),key=lambda kv:float(kv[1]['mae_mean'])):
        mae=fmt(100*float(r['mae_mean']))
        if r['mae_seed_sd']:mae+=r'$\pm$'+fmt(100*float(r['mae_seed_sd']))
        rr.append([names(m),esc(r['setting']).replace(r'\_', ' '),r['n_seeds'],mae,fmt(100*float(r['rmse_mean']))+'/'+fmt(100*float(r['p95_ae_mean']))])
    tab('historical_xjtu','Historical XJTU screen: the lowest archived dataset-level MAE setting for each of nineteen families. This is a development-selected archive, not an independent source-validation-selected ranking.','historical','llrcc',['Method','Archived setting','Seeds','MAE','RMSE/P95'],rr,fit=True)
    sens = json.loads((EVID/'figure_data/09_structural_sensitivity_data.json').read_text())
    rr=[]
    params=list(dict.fromkeys(r['parameter'] for r in sens))
    ss={(r['dataset'],r['parameter']):r for r in sens if r['metric']=='mae'}
    for param in params:
        for j,val in enumerate(ss[('XJTU',param)]['values']):
            rr.append([esc(param),str(val),*[fmt(ss[(d,param)]['delta_pp'][j]) for d in DATASETS]])
    tab('sensitivity','One-factor structural sensitivity: MAE change (pp) relative to the frozen complete configuration. All other options, including M4 in the M3 scan, remain fixed.','sensitivity','llrrr',['Parameter','Value',*DATASETS],rr,fit=True)
    rr=[]
    for r in read('external/confirmation/summary/paired_intervals.csv'):
        if r['metric']=='mae_pp':
            rr.append([r['comparison'],fmt(r['delta_pp']),r['improved_cells']+'/'+r['cells'],interval(r,'cell'),interval(r,'domain')])
    tab('external_pairs','CALCE paired MAE intervals (pp), 5,000 descriptive resamples of source-averaged cell errors. Wins count cells, not source-model/cell pairs.','externalpairs','lrccc',['Comparison',r'$\Delta$','Wins/total','Cell-stratified CI','Protocol-group CI'],rr,fit=True)


def new_plot():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import numpy as np
    cells=read('external/confirmation/summary/cell_mean_across_sources.csv')
    ids=list(dict.fromkeys(r['cell_id'] for r in cells))
    vals={(r['cell_id'],r['group']):float(r['mae_pp']) for r in cells}
    delta=np.array([vals[(c,'B1234')]-vals[(c,'B')] for c in ids])
    fig,ax=plt.subplots(figsize=(7.3,3.4),layout='constrained')
    ax.barh(ids,delta,color=np.where(delta<0,'#2378a2','#b6533e'),height=.62)
    ax.axvline(0,color='black',lw=.8)
    ax.invert_yaxis()
    ax.set_xlabel('B1234 minus B: cell MAE (SOH pp); negative is better')
    ax.set_xlim(-1.9,4.45)
    ax.spines[['top','right']].set_visible(False)
    for j,x in enumerate(delta):
        ax.text(x+(.07 if x>=0 else -.07),j,f'{x:+.4f}',va='center',ha='left' if x>=0 else 'right',fontsize=9)
    path=DOC/'figures_new'
    path.mkdir(exist_ok=True)
    fig.savefig(path/'12_calce_cell_change.pdf')
    plt.close(fig)


if __name__ == '__main__':
    prepare()
    make_tables()
    new_plot()
    (ROOT/'evidence_manifest.json').write_text(json.dumps({'training_performed':False,'copied_files':COPIES},ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({'copied_files':len(COPIES),'generated_tables':len(list(TABLES.glob('*.tex'))),'training_performed':False}))
